name: Test login action

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  lint-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6

      - name: Validate workflow with actionlint
        uses: docker://rhysd/actionlint:1.7.11

  test-login-valid-identity:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: lint-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6

      - name: Run login action
        id: login
        uses: ./
        with:
          team: nais
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} # Provided as Organization Secret
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }} # Provided as Organization Variable

      - name: Verify registry output is produced
        run: test -n "${{ steps.login.outputs.registry }}"
